name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Check Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

      - name: Check formatting
        run: |
          swift format lint --recursive Sources Tests > format-issues.txt 2>&1 || true
          if [ -s format-issues.txt ]; then
            echo "❌ Formatting issues found:"
            cat format-issues.txt
            exit 1
          else
            echo "✅ All files are properly formatted"
          fi

      - name: Run swiftlint
        run: |
          brew install swiftlint
          swiftlint lint --quiet --reporter github-actions-logging

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    steps:
      - uses: actions/checkout@v4

      - name: Check Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
