name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Check Swift version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

      - name: Check formatting
        run: |
          swift format lint --recursive Sources Tests > format-issues.txt 2>&1 || true
          if [ -s format-issues.txt ]; then
            echo "❌ Formatting issues found:"
            cat format-issues.txt
            exit 1
          else
            echo "✅ All files are properly formatted"
          fi
