name: Deploy DocC

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target TailscaleClient \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path swift-tailscale-client

          # Create index redirect so base URL works
          cat > ./docs/index.html <<'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting to TailscaleClient Documentation</title>
            <meta http-equiv="refresh" content="0; url=documentation/tailscaleclient/">
            <link rel="canonical" href="documentation/tailscaleclient/">
          </head>
          <body>
            <p>Redirecting to <a href="documentation/tailscaleclient/">TailscaleClient Documentation</a>...</p>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
